name: SerraStack CI ğŸš€

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t serrastack-test -f config/Dockerfile .

      - name: Test Container (Smoke Test)
        run: |
          docker run -d --name test-container -p 8082:80 serrastack-test
          sleep 5
          if curl -s localhost:8082 | grep "SerraStack"; then
            echo "âœ… Healthcheck Passed!"
          else
            echo "âŒ Healthcheck Failed!"
            exit 1
          fi

      - name: Cleanup
        run: docker rm -f test-container